name: Hello Workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: node:14-alpine
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
        