name: Hello Workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: node:14-alpine
        env:
            slack_wehbook_url: ${{secrets.slack_wehbook_url}}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Notify on success or Failure
              if: always()
              uses: actions/slack@v1
              with:
                  status: ${{ job.status }}
                  message: "Workflow run ${{ job.status }} for ${{ github.repository}} on branch${{github.ref}}by ${{ github.actor}}"
                  channel: '#hello'
                  token: ${{ secrets.GITHUB_TOKEN}}
            
            
        
