name: Hello Workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: node:14-alpine
        env:
            SLACK_WEHBOOK: ${{ secrets.SLACK_WEHBOOK }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

              
            - name: Slack Notification
              uses: act10ns/slack@v1
              with:
                  status: ${{ job.status }}
                  steps: ${{ toJson(steps) }}
                  channel: '#hello'
              if: always()
            
            
        
