name: Hello Workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: node:14-alpine
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Send Notification on Success
              if: ${{success()}}
              with:
                  message: 'workflow succeeded!'
            - name: Send Notification on Success
              if: ${{ failure() }}
              with:
                  message: 'workflow Failed!'
            
            
        
