name: Hello Workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: node:14-alpine
        steps:
            - name: Notify on success or Failure
              if: always()
              uses: action/notify@v1
              with:
                  status: ${{ job.status }}
                  message: "Workflow run ${{ job.status }} for ${{ github.repository}} on branch${{github.ref}}by ${{ github.actor}}"
                  token: ${{ secrets.GITHUB_TOKEN}}
            
            
        
